name: habituai

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    run-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Run Tests
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
            - run: npm install
            - run: npm run build

    run-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Run Tests
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
            - run: npm install
            - run: npm run test
